name: CI - Deploy to Github Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
      - uses: actions/checkout@v4

      - name: Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install

      - name: Build Vitepress
        run: npx vitepress build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.vitepres/dist
          enable_jekyll: false
          publish_branch: gh-pages

      # Runs a set of commands using the runners shell
      - name: Its works
        run: |
          echo "----------------------------"
          echo Yes, it works
          echo "----------------------------"
